# Generated by Django 4.0.8 on 2023-01-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendcustomemailschedulerlog',
            name='links_clicked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sendgroupsemailschedulerlog',
            name='links_clicked_count',
            field=models.IntegerField(default=0),
        ),
    ]
