# Generated by Django 4.0.8 on 2022-11-28 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendcustomemailscheduler',
            name='status',
        ),
        migrations.AddField(
            model_name='sendgroupsemailschedulerlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SendCustomEmailSchedulerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED')], default='PENDING', max_length=250)),
                ('emails_view_count', models.IntegerField(default=0)),
                ('sent_mail_count', models.IntegerField(default=0)),
                ('read_mail_count', models.IntegerField(default=0)),
                ('links_clicked', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('send_custom_email_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.sendcustomemailscheduler')),
            ],
        ),
    ]
