# Generated by Django 4.0.8 on 2023-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_sendcustomemailschedulerlog_links_clicked_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendgroupsemailscheduler',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
