# Generated by Django 4.0.8 on 2023-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_sendgroupsemailscheduler_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcustomemailscheduler',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
