# Generated by Django 4.0.8 on 2023-03-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_sendcustomemailscheduler_scheduled_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendCustomEmailSchedulerLog',
        ),
    ]
