# Generated by Django 4.0.8 on 2023-03-21 15:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companyemployee_company'),
        ('events', '0003_eventregister_user_alter_eventregister_gender'),
        ('communications', '0006_delete_sendcustomemailschedulerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailScheduler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message_type', models.CharField(blank=True, choices=[('CUSTOM', 'CUSTOM'), ('GROUP', 'GROUP'), ('HIGHVALUECONTENT', 'HIGHVALUECONTENT'), ('CAREER', 'CAREER'), ('EVENT', 'EVENT'), ('OTHERS', 'OTHERS')], max_length=250, null=True)),
                ('email_list', models.TextField()),
                ('email_subject', models.CharField(max_length=250)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=1500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('events', models.ManyToManyField(blank=True, to='events.event')),
                ('groups', models.ManyToManyField(blank=True, to='companies.group')),
            ],
        ),
        migrations.RemoveField(
            model_name='sendgroupsemailscheduler',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sendgroupsemailscheduler',
            name='email_to',
        ),
        migrations.RemoveField(
            model_name='sendgroupsemailschedulerlog',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sendgroupsemailschedulerlog',
            name='send_groups_email_scheduler',
        ),
        migrations.DeleteModel(
            name='SendCustomEmailScheduler',
        ),
        migrations.DeleteModel(
            name='SendGroupsEmailScheduler',
        ),
        migrations.DeleteModel(
            name='SendGroupsEmailSchedulerLog',
        ),
    ]
