# Generated by Django 4.0.8 on 2023-03-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_sendemailscheduler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemailscheduler',
            name='email_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
