# Generated by Django 4.0.8 on 2023-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_value_contents', '0005_highvaluecontent_lead_contacts_and_more'),
        ('communications', '0008_alter_sendemailscheduler_email_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemailscheduler',
            name='high_value_contents',
            field=models.ManyToManyField(blank=True, to='high_value_contents.highvaluecontent'),
        ),
        migrations.AlterField(
            model_name='sendemailscheduler',
            name='message_type',
            field=models.CharField(blank=True, choices=[('CUSTOM', 'CUSTOM'), ('LEAD_GROUP', 'LEAD_GROUP'), ('SCHEDULE_GROUP', 'SCHEDULE_GROUP'), ('HIGHVALUECONTENT', 'HIGHVALUECONTENT'), ('CAREER', 'CAREER'), ('EVENT', 'EVENT'), ('OTHERS', 'OTHERS')], max_length=250, null=True),
        ),
    ]
