# Generated by Django 4.0.8 on 2023-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_sendemailscheduler_high_value_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemailscheduler',
            name='message_type',
            field=models.CharField(blank=True, choices=[('CUSTOM', 'CUSTOM'), ('LEAD_GROUP', 'LEAD_GROUP'), ('SCHEDULE_GROUP', 'SCHEDULE_GROUP'), ('HIGHVALUECONTENT', 'HIGHVALUECONTENT'), ('CAREER', 'CAREER'), ('EVENT', 'EVENT'), ('ALL', 'ALL'), ('OTHERS', 'OTHERS')], max_length=250, null=True),
        ),
    ]
