# Generated by Django 4.0.8 on 2022-10-27 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9cb8def8-d89c-409f-bd3f-24e2a145f60e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
