# Generated by Django 4.0.8 on 2022-10-27 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('134a82bc-a2c6-4108-ac78-f1e9c6c249e3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
