# Generated by Django 4.0.8 on 2022-10-27 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('61a3c34e-4526-4f55-a926-501b2b8aef32'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
