# Generated by Django 4.0.8 on 2022-10-27 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d154d778-dcbc-411d-acb9-56bcb17d41c3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
