# Generated by Django 4.0.8 on 2022-10-27 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5648173-3f25-4bc0-956e-47bb9157702a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
