# Generated by Django 4.0.8 on 2022-10-27 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e00eda83-21d9-40bb-81cb-32862935c4c5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
