# Generated by Django 4.0.8 on 2022-10-28 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1df506f1-2988-4688-8190-63f92ca78a21'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
