# Generated by Django 4.0.8 on 2022-10-28 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e8303b0-04cd-4ca6-8fc2-d36e965b9db2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
