# Generated by Django 4.0.8 on 2022-10-28 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27fb1149-9c4a-447a-b208-5b9e27daf5e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
