# Generated by Django 4.0.8 on 2022-10-28 17:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bba32ed1-c8bc-49f7-b10e-4f39e1ad7d35'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
