# Generated by Django 4.0.8 on 2022-10-28 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db88a265-a5b6-4324-b811-9b4678c30b5a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
