# Generated by Django 4.0.8 on 2022-10-29 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26c5ded3-501a-445c-9fa5-547310f2970a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
