# Generated by Django 4.0.8 on 2022-10-29 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d6586038-ff21-42df-aaba-36b9aa5df69b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
