# Generated by Django 4.0.8 on 2022-10-31 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f18a34d-4f5c-4fe3-b460-1f29167ba00f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
