# Generated by Django 4.0.8 on 2022-10-31 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38d24ada-68e3-48ac-99af-1f0fcdc1142f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
