# Generated by Django 4.0.8 on 2022-10-31 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf8e46fc-2c21-429f-b92c-4427e3a8f649'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
