# Generated by Django 4.0.8 on 2022-10-31 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08514ff9-5e80-49a8-bfc5-0f3a73f41f9e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
