# Generated by Django 4.0.8 on 2022-11-01 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e21816b-f830-4a10-99f6-e0930a8a7ab4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
