# Generated by Django 4.0.8 on 2022-11-01 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf846701-0a53-45d4-bd9a-9d01840c5795'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
