# Generated by Django 4.0.8 on 2022-11-02 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d04a86e5-79d3-4629-943f-92a69f5f6108'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
