# Generated by Django 4.0.8 on 2022-11-02 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_userprofile_options_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1a90f53-4d0d-4a19-8b69-be228492c1ef'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
