# Generated by Django 4.0.8 on 2022-11-02 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a687002-83eb-4069-a759-29073d11fc26'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
