# Generated by Django 4.0.8 on 2022-11-02 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f67d2a7-5dd6-46e0-a926-d30a50c60278'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
