# Generated by Django 4.0.8 on 2022-11-07 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6f0746f-4edd-4d2f-9770-26379cea842b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
