# Generated by Django 4.0.8 on 2022-11-07 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3387c8a5-11f1-4bbe-bf72-3d6e3893fe0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
