# Generated by Django 4.0.8 on 2022-10-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_end',
            new_name='start_date',
        ),
    ]
