# Generated by Django 4.0.8 on 2022-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_start_end_event_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
    ]
