# Generated by Django 4.0.8 on 2023-03-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_logo'),
        ('events', '0003_eventregister_user_alter_eventregister_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregister',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
