# Generated by Django 4.0.8 on 2022-10-24 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=250)),
                ('lead_source', models.CharField(choices=[('SKILLS_APP', 'SKILLS_APP'), ('WHATSAPP', 'WHATSAPP'), ('GOOGLE', 'GOOGLE'), ('BLOG', 'BLOG'), ('FACEBOOK', 'FACEBOOK'), ('FRIENDS', 'FRIENDS'), ('WEBINAR', 'WEBINAR'), ('NEWS', 'NEWS'), ('OTHERS', 'OTHERS')], max_length=250)),
                ('verified', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('category', models.CharField(choices=[('NOT_AWARE', 'NOT_AWARE'), ('PROBLEM_AWARE', 'PROBLEM_AWARE'), ('INFORMATION', 'INFORMATION'), ('BUYING_NOW', 'BUYING_NOW')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
