# Generated by Django 4.0.8 on 2022-12-02 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(blank=True, help_text='Mr, Mrs, Dr etc.', max_length=50, null=True)),
                ('lead_type', models.CharField(blank=True, choices=[('CONTACTUS', 'CONTACTUS'), ('HIGHVALUECONTENT', 'HIGHVALUECONTENT')], max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lead_thumbnail')),
                ('middle_name', models.CharField(blank=True, max_length=250, null=True)),
                ('job_title', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('want', models.CharField(blank=True, choices=[('CHILD', 'CHILD'), ('SIBLING', 'SIBLING'), ('SELF', 'SELF'), ('CHILD_AND_SELF', 'CHILD_AND_SELF')], help_text='Who want to learn', max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=250)),
                ('lead_source', models.CharField(choices=[('SKILLS_APP', 'SKILLS_APP'), ('WHATSAPP', 'WHATSAPP'), ('GOOGLE', 'GOOGLE'), ('BLOG', 'BLOG'), ('FACEBOOK', 'FACEBOOK'), ('FRIENDS', 'FRIENDS'), ('WEBINAR', 'WEBINAR'), ('NEWS', 'NEWS'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=250)),
                ('is_safe', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('NOT_AWARE', 'NOT_AWARE'), ('PROBLEM_AWARE', 'PROBLEM_AWARE'), ('INFORMATION', 'INFORMATION'), ('BUYING_NOW', 'BUYING_NOW')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
