# Generated by Django 4.0.8 on 2022-10-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='assigned_marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='groups', to='companies.group'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
