# Generated by Django 4.0.8 on 2022-12-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='assigned_marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='lead_groups', to='companies.group'),
        ),
    ]
