# Generated by Django 4.0.8 on 2023-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontact',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('CONTACT_US', 'Contact Us'), ('HIGH_VALUE_CONTENT', 'High Value Content')], max_length=250, null=True),
        ),
    ]
