# Generated by Django 4.0.8 on 2022-10-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_owner_alter_group_company'),
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcontact',
            name='group',
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='lead_groups', to='companies.group'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='prefix',
            field=models.CharField(blank=True, help_text='Mr, Mrs, Dr etc.', max_length=50, null=True),
        ),
    ]
