# Generated by Django 4.0.8 on 2022-10-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_group_id'),
        ('leads', '0003_remove_leadcontact_group_leadcontact_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='company',
            field=models.ForeignKey(default='9c386f58-4b94-42d0-b326-b4d26958116f', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
