# Generated by Django 4.0.8 on 2023-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leadcontact_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='paying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='send_email',
            field=models.BooleanField(null=True),
        ),
    ]
