# Generated by Django 4.0.8 on 2022-10-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadcontact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='message',
            field=models.TextField(default='I will like to subscribe to instinchub'),
            preserve_default=False,
        ),
    ]
