# Generated by Django 4.0.8 on 2023-02-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_headquater_company_headquarter'),
        ('leads', '0004_leadcontact_paying_leadcontact_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_companies', to='companies.company'),
        ),
    ]
