# Generated by Django 4.0.8 on 2022-11-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('high_value_contents', '0002_alter_leadboardstorage_id'),
        ('leads', '0005_leadcontact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='high_value_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contacts', to='high_value_contents.highvaluecontent'),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='leadcontact',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
