# Generated by Django 4.0.8 on 2022-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadcontact_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcontact',
            name='want',
            field=models.CharField(blank=True, choices=[('CHILD', 'CHILD'), ('SIBLING', 'SIBLING'), ('SELF', 'SELF'), ('CHILD_AND_SELF', 'CHILD_AND_SELF')], help_text='Who want to learn', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='category',
            field=models.CharField(blank=True, choices=[('NOT_AWARE', 'NOT_AWARE'), ('PROBLEM_AWARE', 'PROBLEM_AWARE'), ('INFORMATION', 'INFORMATION'), ('BUYING_NOW', 'BUYING_NOW')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadcontact',
            name='lead_source',
            field=models.CharField(choices=[('SKILLS_APP', 'SKILLS_APP'), ('WHATSAPP', 'WHATSAPP'), ('GOOGLE', 'GOOGLE'), ('BLOG', 'BLOG'), ('FACEBOOK', 'FACEBOOK'), ('FRIENDS', 'FRIENDS'), ('WEBINAR', 'WEBINAR'), ('NEWS', 'NEWS'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=250),
        ),
    ]
