# Generated by Django 4.0.8 on 2022-11-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_leadcontact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadcontact',
            name='message',
        ),
    ]
