# Generated by Django 4.0.8 on 2023-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_job_applicants_applicant_job_job_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='staff',
        ),
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, to='careers.applicant'),
        ),
    ]
