# Generated by Django 4.0.8 on 2023-01-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_remove_applicant_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicanteducation',
            old_name='still_working',
            new_name='still_schooling',
        ),
    ]
