# Generated by Django 4.0.8 on 2023-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_rename_still_working_applicanteducation_still_schooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('software_dev', 'Software Development'), ('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('ai', 'Artificial Intelligence'), ('devops', 'DevOps'), ('cloud_computing', 'Cloud Computing'), ('frontend_dev', 'Front-End Development'), ('backend_dev', 'Back-End Development'), ('fullstack_dev', 'Full-Stack Development'), ('ui_ux_design', 'UI/UX Design'), ('product_management', 'Product Management'), ('project_management', 'Project Management'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('customer_support', 'Customer Support'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('content_creation', 'Content Creation'), ('copywriting', 'Copywriting'), ('editing', 'Editing'), ('proofreading', 'Proofreading')], max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_experience_level',
            field=models.CharField(choices=[('entry', 'Entry-level'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('executive', 'Executive')], max_length=250),
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_types',
        ),
        migrations.AddField(
            model_name='job',
            name='job_types',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
