# Generated by Django 4.0.8 on 2023-01-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyemployee_invited_alter_companyemployee_role'),
        ('feedbacks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
