# Generated by Django 4.0.8 on 2023-02-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedback_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='action',
            field=models.CharField(choices=[('MOBILE-CALL', 'MOBILE-CALL'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('WHATSAPP', 'WHATSAPP'), ('ZOOM', 'Zoom'), ('GOOGLE-MEET', 'GOOGLE-MEET')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='next_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
