# Generated by Django 4.0.8 on 2022-10-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_group_id'),
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscriber',
            name='company',
            field=models.ForeignKey(default='235d6e86-78e1-4f4b-a09f-1131b07cc330', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companysubscriber',
            name='group',
            field=models.ForeignKey(default='235d6e86-78e1-4f4b-a09f-1131b07cc330', on_delete=django.db.models.deletion.CASCADE, to='companies.group'),
            preserve_default=False,
        ),
    ]
