# Generated by Django 4.0.8 on 2022-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_companysubscriber_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscriber',
            name='first_name',
            field=models.CharField(default='sss', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysubscriber',
            name='last_name',
            field=models.CharField(default='favour', max_length=250),
            preserve_default=False,
        ),
    ]
