# Generated by Django 4.0.8 on 2022-10-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_companysubscriber_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscriber',
            name='message',
            field=models.TextField(default='I want to subscribe for newsletter'),
            preserve_default=False,
        ),
    ]
