# Generated by Django 4.0.8 on 2022-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_companysubscriber_on_leadboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscriber',
            options={'ordering': ['-timestamp']},
        ),
    ]
