# Generated by Django 4.0.8 on 2022-12-23 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='invited',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('MARKETER', 'MARKETER')], max_length=250, null=True),
        ),
    ]
