# Generated by Django 4.0.8 on 2022-10-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_owner_alter_group_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('2-10', '2-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5001-10000', '5001-10000'), ('10000-+', '10000-+')], max_length=250),
        ),
        migrations.AlterField(
            model_name='group',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
