# Generated by Django 4.0.8 on 2022-10-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_company_size_alter_group_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Company',
            new_name='company',
        ),
    ]
