# Generated by Django 4.0.8 on 2023-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_email_sent_count_company_premium_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='premium_access',
            field=models.BooleanField(default=False),
        ),
    ]
