# Generated by Django 4.0.8 on 2022-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-timestamp']},
        ),
    ]
