# Generated by Django 4.0.8 on 2023-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_premium_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvite',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('DEACTIVATED', 'DEACTIVATED')], default='PENDING', max_length=250),
        ),
    ]
