# Generated by Django 4.0.8 on 2023-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('marketer', 'MARKETER')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('marketer', 'MARKETER')], max_length=250, null=True),
        ),
    ]
