# Generated by Django 4.0.8 on 2023-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_companyemployee_role_alter_companyinvite_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyemployee',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('MARKETER', 'MARKETER')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('MARKETER', 'MARKETER')], max_length=250, null=True),
        ),
    ]
