# Generated by Django 4.0.8 on 2022-12-02 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighValueContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.FileField(blank=True, upload_to='downloads')),
                ('pdf_file', models.FileField(blank=True, upload_to='downloads')),
                ('link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('vimeo_link', models.URLField(blank=True, null=True)),
                ('vimeo_hash_key', models.URLField(blank=True, null=True)),
                ('schedule_link', models.URLField(blank=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.group')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHighValueContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('lead_source', models.CharField(choices=[('SKILLS_APP', 'SKILLS_APP'), ('WHATSAPP', 'WHATSAPP'), ('GOOGLE', 'GOOGLE'), ('BLOG', 'BLOG'), ('FACEBOOK', 'FACEBOOK'), ('FRIENDS', 'FRIENDS'), ('WEBINAR', 'WEBINAR'), ('NEWS', 'NEWS'), ('OTHERS', 'OTHERS')], max_length=250)),
                ('verified', models.BooleanField(default=False)),
                ('is_safe', models.BooleanField(default=False)),
                ('want', models.CharField(max_length=250)),
                ('on_leadboard', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('high_value_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='high_value_contents.highvaluecontent')),
            ],
        ),
    ]
