# Generated by Django 4.0.8 on 2022-10-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_alter_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighValueContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='storages')),
                ('link_1', models.URLField(blank=True, null=True)),
                ('link_2', models.URLField(blank=True, null=True)),
                ('link_3', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
