# Generated by Django 4.0.8 on 2023-01-09 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('high_value_contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highvaluecontent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highvaluecontent',
            name='last_edit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edit_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
