# Generated by Django 4.0.8 on 2023-01-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_value_contents', '0002_highvaluecontent_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highvaluecontent',
            old_name='pdf_file',
            new_name='file',
        ),
    ]
