# Generated by Django 4.0.8 on 2022-11-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_group_id'),
        ('high_value_contents', '0002_alter_leadboardstorage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='highvaluecontent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.group'),
        ),
    ]
