# Generated by Django 4.0.8 on 2022-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_value_contents', '0003_highvaluecontent_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highvaluecontent',
            options={'ordering': ['-timestamp']},
        ),
    ]
