# Generated by Django 4.0.8 on 2023-03-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_leadcontact_company'),
        ('high_value_contents', '0004_downloadhighvaluecontent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highvaluecontent',
            name='lead_contacts',
            field=models.ManyToManyField(blank=True, to='leads.leadcontact'),
        ),
        migrations.DeleteModel(
            name='DownloadHighValueContent',
        ),
    ]
