# Generated by Django 4.0.8 on 2022-12-02 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('minutes', models.IntegerField()),
                ('meeting_link', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserScheduleCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age_range', models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-30', '25-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41+', '41+')], max_length=5, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('communication_medium', models.CharField(choices=[('CALL', 'CALL'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('WHATSAPP', 'WHATSAPP'), ('ZOOM', 'Zoom'), ('GOOGLE-MEET', 'GOOGLE-MEET')], max_length=250)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('employed', models.BooleanField(blank=True, null=True)),
                ('other_training', models.BooleanField(blank=True, null=True)),
                ('other_training_lesson', models.CharField(blank=True, max_length=200, null=True)),
                ('will_pay', models.BooleanField(blank=True, help_text='Willing to invest in learning financially?', null=True)),
                ('income_range', models.CharField(blank=True, help_text='Monthly income range.', max_length=200, null=True)),
                ('knowledge_scale', models.IntegerField(blank=True, null=True)),
                ('have_laptop', models.BooleanField(blank=True, null=True)),
                ('will_get_laptop', models.BooleanField(blank=True, null=True)),
                ('when_get_laptop', models.CharField(blank=True, max_length=200, null=True)),
                ('good_internet', models.BooleanField(blank=True, null=True)),
                ('weekly_commitment', models.CharField(blank=True, max_length=50, null=True)),
                ('saturday_check_in', models.BooleanField(blank=True, null=True)),
                ('hours_per_week', models.CharField(max_length=20)),
                ('catch_up_per_hours_weeks', models.CharField(blank=True, max_length=20, null=True)),
                ('more_details', models.TextField(blank=True, null=True)),
                ('kids_count', models.IntegerField(blank=True, null=True)),
                ('kids_years', models.CharField(blank=True, max_length=100, null=True)),
                ('time_close_from_school', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('PARENT', 'PARENT'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=100, null=True)),
                ('eligible', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
