# Generated by Django 4.0.8 on 2022-10-24 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('minutes', models.IntegerField()),
                ('meeting_link', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserScheduleCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('have_laptop', models.BooleanField(default=False)),
                ('good_internet', models.BooleanField(default=False)),
                ('weekly_commitment', models.CharField(max_length=250)),
                ('saturday_check_in', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('PARENT', 'PARENT'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=250)),
                ('will_subscribe', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ManyToManyField(blank=True, related_name='companies', to='companies.group')),
                ('schedule_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedulecall')),
            ],
        ),
    ]
