# Generated by Django 4.0.8 on 2022-12-02 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedulecall',
            name='assigned_marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_schedule_groups', to='companies.group'),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='lead_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contacts', to='leads.leadcontact'),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='schedule_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_calls', to='schedules.schedulecall'),
        ),
        migrations.AddField(
            model_name='schedulecall',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
