# Generated by Django 4.0.8 on 2022-10-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_owner_alter_group_company'),
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedulecall',
            name='group',
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_schedule_groups', to='companies.group'),
        ),
    ]
