# Generated by Django 4.0.8 on 2022-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedulecall',
            name='schedule_category',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RESOLVED', 'RESOLVED')], default='PENDING', max_length=100),
        ),
    ]
