# Generated by Django 4.0.8 on 2023-02-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_companyinvite_status'),
        ('schedules', '0003_userschedulecall_schedule_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedulecall',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userschedulecall',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='schedulecall',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='scheduled_date',
            field=models.DateTimeField(null=True),
        ),
    ]
