# Generated by Django 4.0.8 on 2022-10-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_userschedulecall_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedulecall',
            name='communication_medium',
            field=models.CharField(choices=[('CALL', 'CALL'), ('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('WHATSAPP', 'WHATSAPP'), ('ZOOM', 'Zoom'), ('GOOGLE-MEET', 'GOOGLE-MEET')], default='SMS', max_length=250),
            preserve_default=False,
        ),
    ]
