# Generated by Django 4.0.8 on 2023-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_userschedulecall_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecall',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schedulecall',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulecall',
            name='slug',
            field=models.SlugField(),
        ),
    ]
