# Generated by Django 4.0.8 on 2022-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_userschedulecall_communication_medium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulecall',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='userschedulecall',
            options={'ordering': ['-timestamp']},
        ),
    ]
