# Generated by Django 4.0.8 on 2022-11-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_schedulecall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedulecall',
            name='email',
            field=models.EmailField(default='dev.codertjay@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='will_get_laptop',
            field=models.BooleanField(default=False),
        ),
    ]
