# Generated by Django 4.0.8 on 2023-02-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companyemployee_company'),
        ('schedules', '0006_alter_schedulecall_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecall',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.group'),
        ),
    ]
