# Generated by Django 4.0.8 on 2023-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_schedulecall_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecall',
            name='redirect_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulecall',
            name='redirect_link_title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
