# Generated by Django 4.0.8 on 2022-11-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_leadcontact_message'),
        ('schedules', '0007_userschedulecall_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedulecall',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='userschedulecall',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='age_range',
            field=models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-30', '25-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('41+', '41+')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='employed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='income_range',
            field=models.CharField(blank=True, help_text='Monthly income range.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='kids_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='kids_years',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='knowledge_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='lead_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contacts', to='leads.leadcontact'),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='more_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='other_training',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='other_training_lesson',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='time_close_from_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='when_get_laptop',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userschedulecall',
            name='will_pay',
            field=models.BooleanField(blank=True, help_text='Willing to invest in learning financially?', null=True),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='good_internet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='have_laptop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='saturday_check_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='schedule_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_calls', to='schedules.schedulecall'),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PARENT', 'PARENT'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='weekly_commitment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userschedulecall',
            name='will_get_laptop',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
