# Generated by Django 4.0.8 on 2023-03-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_userschedulecall_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userschedulecall',
            name='groups',
        ),
    ]
