# Generated by Django 4.0.5 on 2023-01-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_tax_ussds', '0002_easytaxussd_state_alter_easytaxussd_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easytaxussd',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
    ]
